name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Change default timezone
        run: |
          date -R
          sudo timedatectl set-timezone Asia/Shanghai
          date -R

      - uses: actions/checkout@v1

      - name: Init nodejs env
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Init gitbook env
        run: |
          npm install gitbook-cli -g
          gitbook install
          gitbook build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY_CLOUDCONE }}
          SOURCE: '_book/'
          REMOTE_HOST: ${{ secrets.HOST_CLOUDCONE }}
          REMOTE_USER: ${{ secrets.USER_CLOUDCONE }}
          TARGET: '~/gitbook-repo/above-coding'
